#' Draw posterior samples for one quantile
#'
#' Thin wrapper around [rstan::sampling()] that targets the compiled `bqmm`
#' Stan model (`stanmodels$bqmm`, generated by rstantools; see SETUP.md) and
#' surfaces basic convergence checks.
#'
#' @param standata Stan data list from [bqmm_standata()].
#' @param model Name of the compiled Stan model to use (`"bqmm"` for diagonal
#'   random effects, `"bqmm_corr"` for the correlated model).
#' @param chains,iter,warmup,cores,seed,control Sampler settings.
#' @param ... Forwarded to [rstan::sampling()].
#' @return A `stanfit` object.
#' @keywords internal
bqmm_sample <- function(standata, model = "bqmm", chains = 4, iter = 2000,
                        warmup = floor(iter / 2),
                        cores = 1L, seed = NULL,
                        control = list(adapt_delta = 0.95), ...) {
  if (!exists("stanmodels", mode = "list")) {
    stop(
      "The compiled Stan model is not available. Run the one-time rstantools ",
      "setup described in SETUP.md, then devtools::load_all().",
      call. = FALSE
    )
  }
  if (is.null(seed)) seed <- sample.int(.Machine$integer.max, 1L)

  args <- list(
    object  = stanmodels[[model]],
    data    = standata,
    chains  = chains,
    iter    = iter,
    warmup  = warmup,
    cores   = cores,
    seed    = seed,
    control = control
  )
  fit <- do.call(rstan::sampling, c(args, list(...)))
  check_convergence(fit)
  fit
}

#' Warn on convergence problems
#'
#' @param fit A `stanfit` object.
#' @keywords internal
check_convergence <- function(fit) {
  smry <- rstan::summary(fit)$summary
  rhat <- smry[, "Rhat"]
  ess  <- smry[, "n_eff"]
  if (any(rhat > 1.01, na.rm = TRUE)) {
    warning("Some Rhat > 1.01; chains may not have converged.", call. = FALSE)
  }
  if (any(ess < 100, na.rm = TRUE)) {
    warning("Some effective sample sizes < 100; consider more iterations.",
            call. = FALSE)
  }
  div <- rstan::get_num_divergent(fit)
  if (!is.null(div) && div > 0) {
    warning(sprintf("%d divergent transition(s); consider raising adapt_delta.",
                    div), call. = FALSE)
  }
  invisible(fit)
}
